- tags:
    - install
  block:
    - include_tasks: "repositories_debian.yml"
      when: ansible_os_family == "Debian"

    - include_tasks: "repositories_redhat.yml"
      when: ansible_os_family == "RedHat"

    - name: Create yggdrasil group
      group:
        name: yggdrasil
        system: yes
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install package
      package:
        name: yggdrasil
        state: present

- tags:
    - configure
  block:
    - name: Generate automatic configuration
      shell: yggdrasil -genconf > "{{ yggdrasil_config_path }}"
      args:
        creates: "{{ yggdrasil_config_path }}"
      when: yggdrasil_generate_configuration
      notify: restart yggdrasil

    - name: Generate configuration
      template:
        dest: "{{ yggdrasil_config_path }}"
        src: yggdrasil.conf.j2
        mode: 0600
      when: yggdrasil_manage_configuration
      notify: restart yggdrasil

- name: Enable the service
  service:
    name: yggdrasil
    state: started
    enabled: yes
  tags:
    - service
